config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  get 'expenses/new'
  post 'expenses/new'

  get 'welcome/index'
  #root 'welcome#index'
  resources :expenses



  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  get	'/users/index'
  #root 'users#index'

#GET	/users/1	show	page to show user with id 1
	get '/users/new'
	#post '/users'	, to: 'users#destroy'#create	create a new user
  get	'/users/1/edit'	, to: 'users#edit' #edit	page to edit user with id 1
  #patch	'/users/1'	#update	update user with id 1
  post	'/users/1/destroy'	, to: 'users#destroy' #destroy	delete user with id 1



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @users = User.all
  end

  # GET /expenses/1/edit
  def edit
    @users = User.all
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)


    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount_cents, :user_id, user_ids: [])
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :expense_title %>
  </div>

  <div class="field">
    <%= form.label :amount_cents %>
    <%= form.text_field :amount_cents, id: :expense_amount_cents %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.select(
      :user_id,
      options_for_select(@users.map { |e| [e.name, e.id] }))
    %>
  </div>

  <div class="field">
  <%= form.label :users %>
    <%= form.select(
      :user_ids,
      options_for_select(@users.map { |e| [e.name, e.id] }),
      {},
      { :multiple => true})
    %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Amount cents</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.title %></td>
        <td><%= expense.amount_cents %></td>
        <td><%= expense.user.name %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @expense.title %>
</p>

<p>
  <strong>Amount cents:</strong>
  <%= @expense.amount_cents %>
</p>

<p>
  <strong>User:</strong>
  <%= @expense.user %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>