config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'sessions/new'

  get 'expenses/new'
  post 'expenses/new'

  get 'welcome/index'
  #root 'welcome#index'
  resources :expenses



  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  get	'/users/index'
  #root 'users#index'

#GET	/users/1	show	page to show user with id 1
	get '/users/new'
	#post '/users'	, to: 'users#destroy'#create	create a new user
  get	'/users/1/edit'	, to: 'users#edit' #edit	page to edit user with id 1
  #patch	'/users/1'	#update	update user with id 1
  post	'/users/1/destroy'	, to: 'users#destroy' #destroy	delete user with id 1



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.google.com/">GAMGF</a>
    by <a href="http://www.google.com/">GAMGF ®</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.google.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Good accounts make good friends", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",    root_path %></li>
        <li><%= link_to "Help",    help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag    'application', media: 'all' %>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<title><%= yield(:title) %> | GAMGF App</title>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>